name: notepad
description: "Flutter Notepad using local database."
publish_to: 'Google Playstore'

version: 1.0.0+1

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  shared_preferences: ^2.2.2
  
  # Bloc Packages
  bloc: ^8.1.3
  flutter_bloc: ^8.1.4
  equatable: ^2.0.5
  get: ^4.6.6

  # Fonts Packages
  google_fonts: ^6.2.1

  # Other Packages
  image_picker: ^1.0.7
  uuid: ^4.3.3
  fluttertoast: ^8.2.4
  intl: ^0.19.0
  path: ^1.9.0
  compress_images_flutter: ^0.0.3+9
  image: ^4.1.7
  path_provider: ^2.1.2
  flutter_lints: ^3.0.0



dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/images/
    - assets/svgs/

